version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./database.sqlite:/app/database.sqlite # Montar el archivo de SQLite
    environment:
      - NODE_ENV=production
